defaults:
  - _self_  # all below configs will override this conf.yaml
  - robot: r1pro
  - task: behavior
  - policy: ???

env_wrapper: 
  _target_: omnigibson.learning.wrappers.RGBWrapper
policy_name: ???  # filled by policy
headless: true  # whether to run in headless mode (no GUI)
eval_on_train_instances: false  # whether to eval on training instances
eval_instance_ids: null  # specific list of instance ids to eval on, if null test on all instances
write_video: true # whether we record videos during rollout
partial_scene_load: false  # whether to only load task-relevant rooms for a specific task
max_steps: null  # max steps per rollout episode, setting to null will use the default value (2 x average human demo completion steps)
log_path: ???
test_hidden: false  # [Internal use only] whether to eval on hidden test instances
save_rollout: false  # whether to save rollout data
perturb_pose: false
perturb_pose_seed: 42

# parallel_evaluator: 
use_parallel_evaluator: false
parallel_evaluator_start_idx: 0
parallel_evaluator_end_idx: 10
